[2024-12-06T17:48:51.063+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T17:48:51.079+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag2_Kafkas3.consume_from_kafka manual__2024-12-06T17:48:49.569493+00:00 [queued]>
[2024-12-06T17:48:51.088+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag2_Kafkas3.consume_from_kafka manual__2024-12-06T17:48:49.569493+00:00 [queued]>
[2024-12-06T17:48:51.089+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-06T17:48:51.103+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): consume_from_kafka> on 2024-12-06 17:48:49.569493+00:00
[2024-12-06T17:48:51.108+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=967) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T17:48:51.110+0000] {standard_task_runner.py:72} INFO - Started process 968 to run task
[2024-12-06T17:48:51.110+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag2_Kafkas3', 'consume_from_kafka', 'manual__2024-12-06T17:48:49.569493+00:00', '--job-id', '544', '--raw', '--subdir', 'DAGS_FOLDER/dag2_Kafkas3.py', '--cfg-path', '/tmp/tmp3y9_f7n0']
[2024-12-06T17:48:51.113+0000] {standard_task_runner.py:105} INFO - Job 544: Subtask consume_from_kafka
[2024-12-06T17:48:51.160+0000] {task_command.py:467} INFO - Running <TaskInstance: dag2_Kafkas3.consume_from_kafka manual__2024-12-06T17:48:49.569493+00:00 [running]> on host d7d86e3077c3
[2024-12-06T17:48:51.254+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag2_Kafkas3' AIRFLOW_CTX_TASK_ID='consume_from_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T17:48:49.569493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T17:48:49.569493+00:00'
[2024-12-06T17:48:51.256+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T17:48:56.279+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:01.281+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:06.282+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:11.284+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:16.285+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:21.288+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:26.290+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:31.292+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:36.295+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:41.297+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:46.297+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:51.298+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:49:56.300+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:01.301+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:06.302+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:11.398+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:16.399+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:21.400+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:26.401+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:31.402+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:36.404+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:41.939+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:46.940+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:51.941+0000] {logging_mixin.py:190} INFO - No message received
[2024-12-06T17:50:53.731+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-12-06T17:50:53.736+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-06T17:50:53.739+0000] {process_utils.py:132} INFO - Sending 15 to group 968. PIDs of all processes in the group: [968]
[2024-12-06T17:50:53.740+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 968
[2024-12-06T17:50:56.942+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-06T17:50:56.962+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T17:50:57.006+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=968, status='terminated', exitcode=0, started='17:48:50') (968) terminated with exit code 0
