[2024-12-07T21:06:06.077+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T21:06:06.092+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag2_kafka_s3.load_to_s3 manual__2024-12-07T21:02:53.681406+00:00 [queued]>
[2024-12-07T21:06:06.101+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag2_kafka_s3.load_to_s3 manual__2024-12-07T21:02:53.681406+00:00 [queued]>
[2024-12-07T21:06:06.102+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-07T21:06:06.115+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-12-07 21:02:53.681406+00:00
[2024-12-07T21:06:06.121+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=476) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T21:06:06.122+0000] {standard_task_runner.py:72} INFO - Started process 478 to run task
[2024-12-07T21:06:06.123+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag2_kafka_s3', 'load_to_s3', 'manual__2024-12-07T21:02:53.681406+00:00', '--job-id', '598', '--raw', '--subdir', 'DAGS_FOLDER/dag2_kafka_s3.py', '--cfg-path', '/tmp/tmp88xav960']
[2024-12-07T21:06:06.125+0000] {standard_task_runner.py:105} INFO - Job 598: Subtask load_to_s3
[2024-12-07T21:06:06.165+0000] {task_command.py:467} INFO - Running <TaskInstance: dag2_kafka_s3.load_to_s3 manual__2024-12-07T21:02:53.681406+00:00 [running]> on host d7d86e3077c3
[2024-12-07T21:06:06.253+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag2_kafka_s3' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T21:02:53.681406+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T21:02:53.681406+00:00'
[2024-12-07T21:06:06.254+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T21:06:06.278+0000] {logging_mixin.py:190} INFO - No messages to process
[2024-12-07T21:06:06.279+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-07T21:06:06.288+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T21:06:06.289+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag2_kafka_s3, task_id=load_to_s3, run_id=manual__2024-12-07T21:02:53.681406+00:00, execution_date=20241207T210253, start_date=20241207T210606, end_date=20241207T210606
[2024-12-07T21:06:06.338+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-07T21:06:06.355+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T21:06:06.357+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
