[2024-12-07T21:14:00.582+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T21:14:00.598+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag2_kafka_s3.test_s3_connection manual__2024-12-07T21:13:58.752390+00:00 [queued]>
[2024-12-07T21:14:00.608+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag2_kafka_s3.test_s3_connection manual__2024-12-07T21:13:58.752390+00:00 [queued]>
[2024-12-07T21:14:00.609+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-07T21:14:00.624+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_s3_connection> on 2024-12-07 21:13:58.752390+00:00
[2024-12-07T21:14:00.631+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=580) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T21:14:00.633+0000] {standard_task_runner.py:72} INFO - Started process 582 to run task
[2024-12-07T21:14:00.633+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag2_kafka_s3', 'test_s3_connection', 'manual__2024-12-07T21:13:58.752390+00:00', '--job-id', '599', '--raw', '--subdir', 'DAGS_FOLDER/dag2_kafka_s3.py', '--cfg-path', '/tmp/tmpc2buv19n']
[2024-12-07T21:14:00.635+0000] {standard_task_runner.py:105} INFO - Job 599: Subtask test_s3_connection
[2024-12-07T21:14:00.679+0000] {task_command.py:467} INFO - Running <TaskInstance: dag2_kafka_s3.test_s3_connection manual__2024-12-07T21:13:58.752390+00:00 [running]> on host d7d86e3077c3
[2024-12-07T21:14:00.768+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag2_kafka_s3' AIRFLOW_CTX_TASK_ID='test_s3_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T21:13:58.752390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T21:13:58.752390+00:00'
[2024-12-07T21:14:00.769+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T21:14:01.289+0000] {logging_mixin.py:190} INFO - Подключение успешно. Найдено 7 бакетов: ['levs-test', 'mybucket', 'reciept-bucket', 'spark', 'test-bucket', 'travel', 'users-add']
[2024-12-07T21:14:01.290+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-07T21:14:01.301+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T21:14:01.302+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag2_kafka_s3, task_id=test_s3_connection, run_id=manual__2024-12-07T21:13:58.752390+00:00, execution_date=20241207T211358, start_date=20241207T211400, end_date=20241207T211401
[2024-12-07T21:14:01.331+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-07T21:14:01.362+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-07T21:14:01.364+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
