[2024-12-04T18:51:47.875+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T18:51:47.940+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: producer.test1 manual__2024-12-04T18:51:45.470465+00:00 [queued]>
[2024-12-04T18:51:47.975+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: producer.test1 manual__2024-12-04T18:51:45.470465+00:00 [queued]>
[2024-12-04T18:51:47.979+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-04T18:51:48.032+0000] {taskinstance.py:2889} INFO - Executing <Task(ProduceToTopicOperator): test1> on 2024-12-04 18:51:45.470465+00:00
[2024-12-04T18:51:48.045+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=719) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T18:51:48.049+0000] {standard_task_runner.py:72} INFO - Started process 720 to run task
[2024-12-04T18:51:48.050+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'producer', 'test1', 'manual__2024-12-04T18:51:45.470465+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/test_dags2.py', '--cfg-path', '/tmp/tmpl1eq46xy']
[2024-12-04T18:51:48.052+0000] {standard_task_runner.py:105} INFO - Job 272: Subtask test1
[2024-12-04T18:51:48.124+0000] {task_command.py:467} INFO - Running <TaskInstance: producer.test1 manual__2024-12-04T18:51:45.470465+00:00 [running]> on host bc436253e42c
[2024-12-04T18:51:48.280+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='producer' AIRFLOW_CTX_TASK_ID='test1' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T18:51:45.470465+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T18:51:45.470465+00:00'
[2024-12-04T18:51:48.283+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T18:51:48.343+0000] {base.py:84} INFO - Retrieving connection 'kafka_connection'
[2024-12-04T18:51:48.356+0000] {produce.py:41} INFO - Producer <cimpl.Producer object at 0x7fe5659c2ca0>
[2024-12-04T18:51:48.360+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/operators/produce.py", line 125, in execute
    for k, v in producer_callable():
                ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dags2.py", line 65, in producer_function
    msg_dict = json.loads(value1)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[2024-12-04T18:51:48.428+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=producer, task_id=test1, run_id=manual__2024-12-04T18:51:45.470465+00:00, execution_date=20241204T185145, start_date=20241204T185147, end_date=20241204T185148
[2024-12-04T18:51:48.493+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T18:51:48.496+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 272 for task test1 (the JSON object must be str, bytes or bytearray, not dict; 720)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/operators/produce.py", line 125, in execute
    for k, v in producer_callable():
                ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dags2.py", line 65, in producer_function
    msg_dict = json.loads(value1)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[2024-12-04T18:51:48.548+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-04T18:51:48.628+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T18:51:48.635+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
