[2024-12-09T08:24:26.972+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T08:24:26.991+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_kafka_avro.test_s3_connection manual__2024-12-09T08:24:25.501922+00:00 [queued]>
[2024-12-09T08:24:27.001+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_kafka_avro.test_s3_connection manual__2024-12-09T08:24:25.501922+00:00 [queued]>
[2024-12-09T08:24:27.002+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-09T08:24:27.017+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_s3_connection> on 2024-12-09 08:24:25.501922+00:00
[2024-12-09T08:24:27.023+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=713) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T08:24:27.025+0000] {standard_task_runner.py:72} INFO - Started process 714 to run task
[2024-12-09T08:24:27.025+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 's3_to_kafka_avro', 'test_s3_connection', 'manual__2024-12-09T08:24:25.501922+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag3_s3_kafka.py', '--cfg-path', '/tmp/tmp5h6qgva5']
[2024-12-09T08:24:27.028+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask test_s3_connection
[2024-12-09T08:24:27.080+0000] {task_command.py:467} INFO - Running <TaskInstance: s3_to_kafka_avro.test_s3_connection manual__2024-12-09T08:24:25.501922+00:00 [running]> on host c23cf8b5bd6f
[2024-12-09T08:24:27.167+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_kafka_avro' AIRFLOW_CTX_TASK_ID='test_s3_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T08:24:25.501922+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T08:24:25.501922+00:00'
[2024-12-09T08:24:27.169+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T08:24:27.660+0000] {logging_mixin.py:190} INFO - Подключение успешно. Найдено 7 бакетов: ['levs-test', 'mybucket', 'reciept-bucket', 'spark', 'test-bucket', 'travel', 'users-add']
[2024-12-09T08:24:27.662+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-09T08:24:27.675+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T08:24:27.676+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=s3_to_kafka_avro, task_id=test_s3_connection, run_id=manual__2024-12-09T08:24:25.501922+00:00, execution_date=20241209T082425, start_date=20241209T082426, end_date=20241209T082427
[2024-12-09T08:24:27.724+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-09T08:24:27.743+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T08:24:27.745+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
