[2024-12-04T13:29:05.366+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T13:29:05.385+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consume.consume manual__2024-12-04T13:29:03.059819+00:00 [queued]>
[2024-12-04T13:29:05.396+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consume.consume manual__2024-12-04T13:29:03.059819+00:00 [queued]>
[2024-12-04T13:29:05.397+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-04T13:29:05.412+0000] {taskinstance.py:2889} INFO - Executing <Task(ConsumeFromTopicOperator): consume> on 2024-12-04 13:29:03.059819+00:00
[2024-12-04T13:29:05.417+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=617) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T13:29:05.419+0000] {standard_task_runner.py:72} INFO - Started process 618 to run task
[2024-12-04T13:29:05.419+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'consume', 'consume', 'manual__2024-12-04T13:29:03.059819+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/test_dags3.py', '--cfg-path', '/tmp/tmph1ntyjvy']
[2024-12-04T13:29:05.421+0000] {standard_task_runner.py:105} INFO - Job 249: Subtask consume
[2024-12-04T13:29:05.465+0000] {task_command.py:467} INFO - Running <TaskInstance: consume.consume manual__2024-12-04T13:29:03.059819+00:00 [running]> on host bc436253e42c
[2024-12-04T13:29:05.575+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='consume' AIRFLOW_CTX_TASK_ID='consume' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T13:29:03.059819+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T13:29:03.059819+00:00'
[2024-12-04T13:29:05.576+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T13:29:05.601+0000] {base.py:84} INFO - Retrieving connection 'kafka_connection'
[2024-12-04T13:30:05.606+0000] {logging_mixin.py:190} INFO - Получено сообщение: <cimpl.Message object at 0x7f66ac0125c0>
[2024-12-04T13:30:05.606+0000] {logging_mixin.py:190} INFO - Получено сообщение: <cimpl.Message object at 0x7f66abe60fc0>
[2024-12-04T13:30:05.607+0000] {logging_mixin.py:190} INFO - Получено сообщение: <cimpl.Message object at 0x7f66abe60d40>
[2024-12-04T13:30:05.612+0000] {logging_mixin.py:190} INFO - Получено сообщение: <cimpl.Message object at 0x7f66abe610c0>
[2024-12-04T13:30:05.612+0000] {logging_mixin.py:190} INFO - Получено сообщение: <cimpl.Message object at 0x7f66abe61140>
[2024-12-04T13:30:05.613+0000] {logging_mixin.py:190} INFO - Получено сообщение: <cimpl.Message object at 0x7f66abe611c0>
[2024-12-04T13:31:05.614+0000] {consume.py:167} INFO - Reached end of log. Exiting.
[2024-12-04T13:31:05.615+0000] {consume.py:182} INFO - committing offset at end_of_operator
[2024-12-04T13:31:05.647+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T13:31:05.648+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=consume, task_id=consume, run_id=manual__2024-12-04T13:29:03.059819+00:00, execution_date=20241204T132903, start_date=20241204T132905, end_date=20241204T133105
[2024-12-04T13:31:05.680+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-04T13:31:05.694+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T13:31:05.696+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
